# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://s13tc2.github.io/cards_demo/"

git_url = "https://github.com/s13tc2/cards_demo/tree/master/"

def custom_doc_links(name): return None
